version: '3.8'

services:
  demo:
    build:
      context: .
      dockerfile: dockerfile
    container_name: exert-nuxt-demo
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./runtime/reception:/app/runtime
    networks:
      - exert-nuxt-net

networks:
  exert-nuxt-net:
    name: exert-nuxt-net
    driver: bridge
